---
# role: nginx
# file: handlers/main.yml

- name: NGINX | Reload service
  become: true
  become_user: root
  ansible.builtin.service:
    name: nginx
    state: reloaded
  listen: reload
  when: not ansible_check_mode
