# role: jomrr.nginx
# file: molecule/resources/playbooks/converge.yml

- name: "PLAYBOOK | Converge | nginx"
  hosts: all
  gather_facts: true
  roles:
    - role: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') }}"
