# role: jomrr.nginx
# file: molecule/resources/playbooks/verify.yml

- name: "PLAYBOOK | Verify | nginx"
  hosts: all
  gather_facts: false
  tasks:
    - name: "Assert true"
      ansible.builtin.assert:
        that: "true"
        fail_msg: "This should never fail"
